<?php
	/*
		Plugin Name: Ultimate Profile Builder by CMSHelpLive
		Plugin URI: http://cmshelplive.com/chl-products/ultimate-profile-builder-pro.html
		Description: Login, registration, edit profile, and password recover shortcodes for the front-end and a complete profile structure.
		Version: 1.1
		Author: Vincent Andrew
		Author URI: http://cmshelplive.com/
		License: GPL2
	*/

	ob_start();
	register_activation_hook ( __FILE__, 'activate_ultimate_profile_builder_plugin' );

	function activate_ultimate_profile_builder_plugin()
	{	
		require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
		global $wpdb;

		$upb_cat=$wpdb->prefix."upb_cat";
		$upb_option=$wpdb->prefix."upb_option";
		$upb_field=$wpdb->prefix."upb_field";
		$upb_cat=$wpdb->prefix."upb_cat";
		$upb_fields =$wpdb->prefix."upb_fields";
		$upb_group =$wpdb->prefix."upb_group";
		
		$sqlcreate = "CREATE TABLE $upb_group
		(id int NOT NULL AUTO_INCREMENT,
			PRIMARY KEY(id),
			name varchar(255)
		)";
		dbDelta( $sqlcreate );
		
		$sqlcreate = "CREATE TABLE $upb_option
		(
			id int NOT NULL AUTO_INCREMENT,
			PRIMARY KEY(id),
			fieldname varchar(255),
			value varchar(255)
		)";
		dbDelta( $sqlcreate );
		
		$insert="INSERT INTO $upb_option
		(
			`id`, `fieldname`, `value`
		)
		VALUES
		(1, 'upb_theme', 'light'),
		(2, 'upb_autogeneratedepass', 'no'),
		(3, 'upb_adminshowhide', 'no'),
		(4, 'upb_editorshowhide', 'no'),
		(5, 'upb_authorshowhide', 'no'),
		(6, 'upb_contributorshowhide', 'no'),
		(7, 'upb_subscribershowhide', 'no'),
		(8, 'upb_usernameshowhide', 'yes'),
		(9, 'upb_firstnameshowhide', 'yes'),
		(10, 'upb_lastnameshowhide', 'yes'),
		(11, 'upb_nicknameshowhide', 'yes'),
		(12, 'upb_displaynamepubliclyshowhide', 'yes'),
		(13, 'upb_emailshowhide', 'yes'),
		(14, 'upb_websiteshowhide', 'yes'),
		(15, 'upb_aimshowhide', 'yes'),
		(16, 'upb_yahooimshowhide', 'yes'),
		(17, 'upb_jabbergoogletalkshowhide', 'yes'),
		(18, 'upb_biographicalinfoshowhide', 'yes'),
		(19, 'upb_profile_list_view', 'table'),
		(20, 'upb_profile_list_column', '4'),
		(21, 'upb_profile_max_resutls', '1'),
		(22, 'Registration_Custom_Text', 'Custom text1 :Lorem ipsum dolor sit amet, consectetur')";
		$wpdb->query($insert);
		//mysql_query($insert);
		
		$sqlcreate = "CREATE TABLE $upb_field
		(
			id int NOT NULL AUTO_INCREMENT,
			PRIMARY KEY(id),
			field_name varchar(255),
			value varchar(255)
		)";
		
		dbDelta( $sqlcreate );
		//mysql_query($sqlcreate);
		
		$upb_values=$wpdb->prefix."upb_values";
		$sqlcreate = "CREATE TABLE $upb_values
		(
			`id` int(11) NOT NULL AUTO_INCREMENT,
			`f_field` int(20) DEFAULT NULL,
			`value` varchar(255) DEFAULT NULL,
			`f_user` int(20) DEFAULT NULL,
			PRIMARY KEY (`id`),
			KEY `f_field` (`f_field`),
			KEY `f_user` (`f_user`)
		)";
		dbDelta( $sqlcreate );
		//mysql_query($sqlcreate);
		
	$sqlcreate = "CREATE TABLE IF NOT EXISTS $upb_fields (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Type` varchar(50) DEFAULT NULL,
  `Name` varchar(256) NOT NULL,
  `Value` varchar(256) DEFAULT NULL,
  `Class` varchar(256) DEFAULT NULL,
  `Max_Length` varchar(256) DEFAULT NULL,
  `Cols` varchar(256) DEFAULT NULL,
  `Rows` varchar(256) DEFAULT NULL,
  `Option_Value` varchar(256) DEFAULT NULL,
  `Description` varchar(256) DEFAULT NULL,
  `Require` varchar(256) DEFAULT NULL,
  `Readonly` varchar(256) DEFAULT NULL,
  `Visibility` varchar(256) DEFAULT NULL,
  `Ordering` varchar(256) DEFAULT NULL,
  `user_group` varchar(256) DEFAULT NULL,
  `registration` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY( `Name`)
)";

dbDelta( $sqlcreate );
//mysql_query($sqlcreate);

}
	add_action('wp_head', 'UltimatePB_adminbar');
	function UltimatePB_adminbar()
	{
		include 'UPB_config.php';
		include 'addremoveadminbar.php';
	}

function theme_name_scripts() {
	wp_enqueue_style( 'style.css', plugin_dir_url(__FILE__) . 'css/style.css');
	wp_enqueue_style( 'pagination.css', plugin_dir_url(__FILE__) . 'css/pagination.css');
	wp_enqueue_style( 'chosen.css', plugin_dir_url(__FILE__) . 'chosen.css');
	wp_enqueue_style( 'upb.css', plugin_dir_url(__FILE__) . 'css/upb.css');
	wp_enqueue_script( 'scriptaculous' );
	wp_enqueue_script( 'password-strength-meter' );
	wp_enqueue_script( 'prism.js',  plugin_dir_url(__FILE__) . 'docsupport/prism.js' );
	
}



function admin_theme_name_scripts() {
	wp_enqueue_style( 'style.css', plugin_dir_url(__FILE__) . 'css/style.css');
	wp_enqueue_style( 'pagination.css', plugin_dir_url(__FILE__) . 'css/pagination.css');
	wp_enqueue_style( 'chosen.css', plugin_dir_url(__FILE__) . 'chosen.css');
	wp_enqueue_style( 'upb.css', plugin_dir_url(__FILE__) . 'css/upb.css');
	wp_enqueue_style( 'SpryTabbedPanels.css', plugin_dir_url(__FILE__) . 'css/SpryTabbedPanels.css');
	wp_enqueue_script( 'scriptaculous' );
	wp_enqueue_script( 'chosen.jquery.js',  plugin_dir_url(__FILE__) . 'chosen.jquery.js');
	wp_enqueue_script( 'prism.js',  plugin_dir_url(__FILE__) . 'docsupport/prism.js' );
	wp_enqueue_script( 'SpryTabbedPanels.js',  plugin_dir_url(__FILE__) . 'js/SpryTabbedPanels.js');
	
}
    add_action( 'wp_enqueue_scripts', 'theme_name_scripts' );
	add_action( 'admin_init', 'admin_theme_name_scripts' );
	add_action('admin_menu', 'ultimate_profile_builder_menu');
	
	function ultimate_profile_builder_menu()
	{
		add_menu_page("Ultimate Profile Builder","Ultimate Profile Builder","manage_options","UltimatePB_settings","UltimatePB_settings",plugins_url('/images/profile-icon2.png', __FILE__));

		add_submenu_page("UltimatePB_settings","Add User Role","Add User Role","manage_options","UltimatePB_Custom_User_Role","UltimatePB_Custom_User_Role");

		add_submenu_page("UltimatePB_settings","Manage Custom Fields","Manage Custom Fields","manage_options","UltimatePB_Fields","UltimatePB_Fields");

		add_submenu_page("","New Field","New Field","manage_options","UltimatePB_Field","UltimatePB_Field");

		add_submenu_page("","Edit Field","Edit Field","manage_options","UltimatePB_Field_edit","UltimatePB_Field_edit");
	}

	function UltimatePB_settings()
	{
		include 'UPB_config.php';
		//include 'initial.php';
		include 'upboption.php';
	}
	function UltimatePB_Fields()
	{
		include 'UPB_config.php';
		include 'UPB_form_fields.php';
	}
	function UltimatePB_Field()
	{
		include 'UPB_config.php';
		include 'UPB_form_field.php';
	}
	function UltimatePB_Custom_User_Role()
	{
		include 'UPB_config.php';
		include 'UPB_user_role.php';
	}
	function UltimatePB_Field_edit()
	{
		include 'UPB_config.php';
		include 'UPB_form_field_edit.php';	
	}
	function UPB_view_profile_fun( $content )
	{

		include 'UPB_config.php';
		include 'UPB_theme.php';
		include 'UPB_view_profile_file.php';
		return $content;
	}
	add_shortcode( 'UPB_profile', 'UPB_view_profile_fun' );

	function UPB_login_fun( $content )
	{
		include 'UPB_config.php';
		include 'UPB_login_file.php';
		return $content;
	}
	add_shortcode( 'UPB_auth', 'UPB_login_fun' );
	function UPB_recover_password_fun( $content )
	{
		include 'UPB_config.php';
		include 'UPB_recover_password_file.php';
		return $content;
	}
	add_shortcode( 'UPB_forgot_password', 'UPB_recover_password_fun' );
	function UPB_register_fun( $content )
	{
		
		wp_enqueue_script( 'mocha.js',  plugin_dir_url(__FILE__) . 'js/mocha.js');
		include 'UPB_config.php';
		include 'UPB_register_file.php';
		//return $content;
	}
	add_shortcode( 'UPB_account', 'UPB_register_fun' );

	function UPB_profile_list_fun( $content )
	{
		include 'UPB_config.php';
		include 'UPB_profile_list_file.php';
		//return $content;
	}
	add_shortcode('UPB_profile_list', 'UPB_profile_list_fun');
	
	
add_action('wp_ajax_fetch_pages', 'UPB_fetch_pages');
add_action('wp_ajax_nopriv_fetch_pages', 'UPB_fetch_pages');
function UPB_fetch_pages()
{
	//include 'UPB_config.php';
	global $wpdb;
	include('fetch_pages.php');die;
	//return false;
	//echo 'test';
}


add_action('wp_ajax_ajaxcalls', 'UPB_ajaxcalls');
add_action('wp_ajax_nopriv_ajaxcalls', 'UPB_ajaxcalls');
function UPB_ajaxcalls()
{
	//include 'UPB_config.php';
	global $wpdb;
	include('ajaxCalls.php');die;
	//return false;
	//echo 'test';
}

add_action('wp_ajax_check_fieldname', 'UPB_check_fieldname');
add_action('wp_ajax_nopriv_check_fieldname', 'UPB_check_fieldname');
function UPB_check_fieldname()
{
	//include 'UPB_config.php';
	global $wpdb;
	include('check_field_name.php');die;
	//return false;
	//echo 'test';
}
?>